# Importando e selecionando as colunas

In [2]:
import pandas as pd

steam_df = pd.read_json('Datasets/SteamDataset_w_HLTB.json')#,engine='pyarrow')

In [8]:
steam_df.sample(5)

,appid,name,scrap_status,type,steam_appid,required_age,is_free,short_description,fullgame,supported_languages,...,hltb_similarity,hltb_main_story,hltb_main_extra,hltb_completionist,hltb_all_styles,ext_user_account_notice,recommendations,metacritic,drm_notice,alternate_appid
177914,NaN,Gloomhaven,Scrap_Sucess,game,780290.0,0,0.0,Lead your band of mercenaries in the land of G...,NaN,"English<strong>*</strong>, French, German, Spa...",...,1.0,82.12,139.93,203.78,124.39,NaN,{'total': 11384},"{'score': 82, 'url': 'https://www.metacritic.c...",NaN,NaN
101680,NaN,Simon the Sorcerer 2 - Legacy Edition (German),Scrap_Sucess,dlc,836320.0,0,1.0,The Legacy Edition of &quot;Simon the Sorcerer...,"{'appid': '678760', 'name': 'Simon the Sorcere...",German<strong>*</strong><br><strong>*</strong>...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53267,NaN,Love & Sex: Second Base - Bree's story,Scrap_Sucess,dlc,2225950.0,0,0.0,Play Love &amp; Sex: Second Base as a girl.,"{'appid': '1264710', 'name': 'Love & Sex: Seco...",English<strong>*</strong><br><strong>*</strong...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168407,NaN,Texas Cheat'Em,Scrap_Sucess,advertising,23510.0,0,0.0,It's not whether you win or lose... it's about...,NaN,"English, French, German, Italian, Spanish - Spain",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73733,NaN,Bounty Hunter: Ocean Diver - Population Pack 5,Scrap_Sucess,dlc,1409224.0,0,0.0,"Give your aquarium a boost in population, this...","{'appid': '830510', 'name': 'Bounty Hunter: Oc...",English,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
steam_df.columns

Index(['appid', 'name', 'scrap_status', 'type', 'steam_appid', 'required_age',
       'is_free', 'short_description', 'fullgame', 'supported_languages',
       'pc_requirements', 'developers', 'publishers', 'platforms',
       'categories', 'release_date', 'controller_support', 'positive',
       'negative', 'tags', 'steamspy_owners', 'spy_status', 'hltb_status',
       'genres', 'achievements', 'price_overview', 'demos', 'hltb_id',
       'hltb_name', 'hltb_alias', 'hltb_similarity', 'hltb_main_story',
       'hltb_main_extra', 'hltb_completionist', 'hltb_all_styles',
       'ext_user_account_notice', 'recommendations', 'metacritic',
       'drm_notice', 'alternate_appid'],
      dtype='object')

In [137]:
#steam_df[['drm_notice','ext_user_account_notice']]
steam_df[steam_df['achievements'].notna()]['achievements']

44                                             {'total': 0}
59        {'total': 14, 'highlighted': [{'name': 'The Fa...
61        {'total': 13, 'highlighted': [{'name': 'Comple...
73        {'total': 26, 'highlighted': [{'name': '听君一席话'...
80        {'total': 19, 'highlighted': [{'name': 'Win On...
                                ...
179165    {'total': 24, 'highlighted': [{'name': 'IT’S A...
179166    {'total': 24, 'highlighted': [{'name': 'The Un...
179175    {'total': 30, 'highlighted': [{'name': 'Proble...
179177    {'total': 47, 'highlighted': [{'name': 'Villag...
179179    {'total': 81, 'highlighted': [{'name': 'IT BEG...
Name: achievements, Length: 42046, dtype: object

In [148]:
#steam_df['required_age'].unique()

print(steam_df.groupby('required_age').count())

              appid    name  scrap_status    type  steam_appid  is_free  \
required_age
0                 0  159624        159624  159624       159624   159624
0                 0       4             4       4            4        4
1                 0       2             2       2            2        2
10                0      49            49      49           49       49
10+               0       1             1       1            1        1
11                0       2             2       2            2        2
12                0      52            52      52           52       52
120               0       1             1       1            1        1
13                0     481           481     481          481      481
14                0      31            31      31           31       31
15                0      15            15      15           15       15
16                0     124           124     124          124      124
17                0    2669          2669    2669         2669     2669
17+               0       1             1       1            1        1
18                0     709           709     709          709      709
19                0       2             2       2            2        2
20                0       2             2       2            2        2
21                0       9             9       9            9        9
3                 0       8             8       8            8        8
5                 0       2             2       2            2        2
6                 0       6             6       6            6        6
7                 0      11            11      11           11       11
7+                0       1             1       1            1        1
8                 0       1             1       1            1        1
9                 0       1             1       1            1        1

              short_description  fullgame  supported_languages  \
required_age
0                        159624     61162               149014
0                             4         1                    4
1                             2         1                    2
10                           49        14                   49
10+                           1         0                    1
11                            2         0                    2
12                           52        22                   52
120                           1         0                    1
13                          481       208                  480
14                           31         1                   31
15                           15         2                   15
16                          124        41                  122
17                         2669      1745                 2657
17+                           1         0                    1
18                          709       375                  706
19                            2         1                    2
20                            2         0                    2
21                            9         5                    9
3                             8         1                    8
5                             2         0                    2
6                             6         1                    6
7                            11         0                   11
7+                            1         0                    1
8                             1         0                    1
9                             1         0                    1

              pc_requirements  ...  hltb_similarity  hltb_main_story  \
required_age                   ...
0                      159624  ...            35545            35545
0                           4  ...                0                0
1                           2  ...                1                1
10                         49  ...               11               11
10+                         1  ...                0                0
11                          2  ...                0                0
12                         52  ...                8                8
120                         1  ...                0                0
13                        481  ...              107              107
14                         31  ...                3                3
15                         15  ...                1                1
16                        124  ...               42               42
17                       2669  ...              569              569
17+                         1  ...                0                0
18                        709  ...              179              179
19                          2  ...                0                0
20                          2  ...                0                0
21                          9  ...                1                1
3                           8  ...                5                5
5                           2  ...                0                0
6                           6  ...                3                3
7                          11  ...                0                0
7+                          1  ...                0                0
8                           1  ...                0                0
9                           1  ...                0                0

              hltb_main_extra  hltb_completionist  hltb_all_styles  \
required_age
0                       35545               35545            35545
0                           0                   0                0
1                           1                   1                1
10                         11                  11               11
10+                         0                   0                0
11                          0                   0                0
12                          8                   8                8
120                         0                   0                0
13                        107                 107              107
14                          3                   3                3
15                          1                   1                1
16                         42                  42               42
17                        569                 569              569
17+                         0                   0                0
18                        179                 179              179
19                          0                   0                0
20                          0                   0                0
21                          1                   1                1
3                           5                   5                5
5                           0                   0                0
6                           3                   3                3
7                           0                   0                0
7+                          0                   0                0
8                           0                   0                0
9                           0                   0                0

              ext_user_account_notice  recommendations  metacritic  \
required_age
0                                1475            15556        4309
0                                   0                1           0
1                                   0                2           1
10                                  2               12           4
10+                                 0                0           0
11                                  0                0           0
12                                  1                6           3
120                                 0                0           0
13                                  9              120          39
14                                  0                1           1
15                                  0                3           1
16                                  1               44          27
17                                 70             1019         482
17+                                 1                1           1
18                                 13              234          34
19                                  0                0           0
20                                  0                1           0
21                                  0                0           0
3                                   0                0           0
5                                   0                0           0
6                                   0                3           0
7                                   0                0           0
7+                                  0                0           0
8                                   0                0           0
9                                   0                0           0

              drm_notice  alternate_appid
required_age
0                    807               14
0                      0                0
1                      0                0
10                     3                0
10+                    0                0
11                     0                0
12                     0                0
120                    0                0
13                    11                0
14                     0                0
15                     0                0
16                     1                0
17                   137                2
17+                    1                0
18                     8                0
19                     0                0
20                     0                0
21                     0                0
3                      0                0
5                      0                0
6                      0                0
7                      0                0
7+                     0                0
8                      0                0
9                      0                0

[25 rows x 39 columns]

In [59]:
def IsEarlyAcess(genres):
    for g in genres:
        if g['description'] == 'Early Access':
            return True
    return False

In [71]:
steam_df_filtered = steam_df[(steam_df['type'] == 'game') & (steam_df['spy_status'] == 'Spy_Scrap_Sucess') & (steam_df['hltb_status'] == 'Found') & (steam_df['is_free'] == False)
& (steam_df['release_date'].str['coming_soon'] == False) & (steam_df['hltb_similarity'] > 0.9) & (steam_df['hltb_main_story'] > 0) & (steam_df['genres'].notnull())]

steam_df_filtered = steam_df_filtered.assign(isEarlyAcess = steam_df_filtered['genres'].apply(lambda genres: IsEarlyAcess(genres)))

steam_df_filtered = steam_df_filtered[(steam_df_filtered['isEarlyAcess'] == False)]

steam_df_filtered = steam_df_filtered[['steam_appid','name','tags','price_overview','hltb_name','hltb_similarity','hltb_main_story','release_date','required_age','positive','negative']]


steam_df_filtered['steam_appid'] = steam_df_filtered['steam_appid'].astype(int)

steam_df_filtered['price_overview'] = steam_df_filtered['price_overview'].str['initial']/100

steam_df_filtered['release_date'] = steam_df_filtered['release_date'].str['date']

steam_df_filtered.reset_index(drop=True,inplace=True)

In [72]:
steam_df_filtered.sample(5)

,steam_appid,name,tags,price_overview,hltb_name,hltb_similarity,hltb_main_story,release_date,required_age,positive,negative
7441,384630,Aviary Attorney,"{'Visual Novel': 68, 'Indie': 58, 'Adventure':...",14.99,Aviary Attorney,1.000000,4.46,"Dec 21, 2015",0,1899.0,106.0
10328,246760,Legends of Eisenwald,"{'Tactical RPG': 213, 'Turn-Based': 208, 'Choi...",19.99,Legends of Eisenwald,1.000000,23.65,"Jul 2, 2015",0,1315.0,407.0
12325,851850,DRAGON BALL Z: KAKAROT,"{'Action': 503, 'RPG': 477, 'Anime': 291, 'Ope...",59.99,Dragon Ball Z: Kakarot,1.000000,30.25,"Jan 16, 2020",0,41476.0,3035.0
9336,315110,Woah Dave!,"{'Action': 27, 'Indie': 27, 'Multiplayer': 15,...",4.99,Woah Dave!,1.000000,0.97,"Oct 30, 2014",0,85.0,27.0
5455,586700,Otherworld: Omens of Summer Collector's Edition,"{'Adventure': 21, 'Casual': 21, 'Nudity': 13, ...",9.99,Otherworld: Omens of Summer,0.979167,2.57,"Feb 6, 2017",0,7.0,1.0

In [110]:
steam_df_filtered.shape

(12597, 11)

Avaliando os tipos das colunas selecionadas

Avaliando se algum preço não está na moeda dolar

In [69]:
steam_df[steam_df['price_overview'].str['currency'] != 'USD']['price_overview'].unique()

array([nan], dtype=object)

# TP7

O dataset utilizado nesse trabalho foi obtido através de consultas via API da loja STEAM e do STEAMSPY,também foram coletados dados via biblioteca de terceiros no HowLongToBeat

|Coluna|Descrição|Tipo|
|------|---------|----|
|appid|Id de identificação na loja steam|Numérico discreto
|name|Nome do jogo|Textual
|scrap_status|Estado do processo de scrap|Textual categórica
|type|Se é um jogo, demo ou dlc|Categorico
|steam_appid|Id de identificação na loja steam, o nome da coluna é diferente quando o dado é extraído via API da steam|Numérico discreto
|required_age|Idade mínima recomendada para o jogo|Numérico discreto
|is_free|Se é um jogo gratuito|Booleano
|short_description|Descrição breve do jogo|Textual
|fullgame|Endereçamento para o jogo completo caso seja uma demo| Dicionário com id e nome do jogo completo
|supported_languages|Lista de linguas suportadas pelo jogo|Textual
|pc_requirements|Dicionário dos requisitos para "rodar" o jogo|Textual
|developers|Nome da desenvolvedora|Textual
|publishers|Nome da publicadora|Textual
|platforms|Dicionário relacionando a plataforma e se o jogo está disponível nela|Booleano
|categories|Dicionário de macro características do jogo|Textual categórica
|release_date|Dicionário relacionando se o jogo já foi lançada e qual a data de lançamento|Temporal
|controller_support|Tipo de suporte a controles|Textual categórica
|positive|Quantidade de avaliações positivas|Numérico discreto
|negative|Quantidade de avaliações negativas|Numérico discreto
|tags|Tags do jogo|Textual categórica
|steamspy_owners|Faixa estimada de proprietários de um jogo|Textual categórica
|spy_status|Estado do processo de scrap dos dados do SteamSpy|Textual categórica
|hltb_status|Estado do processo de scrap dos dados do HowLongToBeat|Textual categórica
|genres|Lista de gêneros do jogo|Textual categórica
|achievements|Quantidade de conquistas e o nome de algumas delas|Numérico discreta e Textual
|price_overview|Dicionário contendo os dados de preço e promoções|Numérico contínuo
|demos|Endereçamento para a demo caso possua| Dicionário com id e nome da demo
|hltb_id|Id de identificação no HowLongToBeat|Numérico discreto
|hltb_name|Nome do jogo no HowLongToBeat|Textual
|hltb_alias|Apelido do jogo no HowLongToBeat|Textual
|hltb_similarity|Grau de similaridade entre o nome do jogo buscado e o nome do jogo encontrado no HLTB|Numérico contínuo
|hltb_main_story|Duração dos objetivos principais do jogo em hrs|Numérico contínuo
|hltb_main_extra|Duração dos extras do jogo em hrs|Numérico contínuo
|hltb_completionist|Duração dos objetivos principais, extras e outros em hrs|Numérico contínuo
|hltb_all_styles|Duração em hrs levando em consideração todos os tipos de jogadores|Numérico contínuo
|ext_user_account_notice|Desconhecido|Textual
|recommendations|Quantidade de avaliações do jogo na loja steam|Numérico discreto
|metacritic|Nota do jogo no site metacritic|Numérico discreto
|drm_notice|Tipo de DRM do jogo|Textual
|alternate_appid|Desconhecido|Numérico discreto

### Colunas que serão utilizadas

|Coluna|Descrição|Tipo|Motivo|Obtenção|
|------|---------|----|------|--------|
|id|Id do jogo na loja steam|Numérico discreto|Caso seja necessário pegar mais dados do dataset original, o ID é uma melhor escolha que |Copiar coluna steam_appid do dataset|
|name|Nome do jogo|Textual|Melhorar a visualização/diferenciação de um jogo pro outro|Copiar coluna name do dataset|
|tags|Tags do jogo|Textural categórica|Serão utilizadas para filtrar os jogos que possuem mais proximidade com o jogo que estamos tentando prever as vendas|Copiar coluna tags do dataset|
|price|Preço não promocional do jogo|Numérico contínuo|Será um dos dados da regressão|Extraído da coluna price_overview do datataset|
|total_duration|Duração dos objetivos principais do jogo|Numérico contínuo|Será um dos dados da regressão|Copiado da coluna hltb_main_story|
|commercialization_days|Total de dias em que o jogo esteve sendo comercializado|Numérico discreto|Será um dos dados da regressão|Extraído da coluna release_date e calcular os dias que se passaram até o dia 31/10/2023
|min_age|Idade recomendada para o jogo|Numérico discreto|Seria um dos dados da regressão, mas há muitos dados faltantes, cerca de 80%|Cópia da coluna required_age do dataset|
|total_reviews|Total de avaliações que o jogo recebeu|Numérico discreto|Será um dos dados da regressão|Soma das colunas positive e negative do dataset|

### 1. a verificação se há dados faltantes e diga qual a estratégia que será tomada em relação a esses dados

Verificação de dados faltantes

Dados faltantes identificados

| Dado | Motivo | Decisão
|--------|--------|---------|
|testy|rtedd|gdsfsa|

### 6. Realize transformações nos dados necessárias para realizar a análise

Organização das colunas e criação de subcolunas com os dados que realmente queremos

- Total de avaliações
- Porcentagem/nota das avaliações
- Tempo de mercado
- Extrair o preço
- Remover os acessos antecipados e outros elementos não desejáveis
- Extrair a data de lançamento
- Remover os com data de lançamento nula
- Converter a data para o formato apropriado

In [100]:
steam_df_filtered.dtypes

steam_appid                 int32
name                       object
tags                       object
price_overview            float64
hltb_name                  object
hltb_similarity           float64
hltb_main_story           float64
release_date       datetime64[ns]
required_age               object
positive                  float64
negative                  float64
dtype: object

In [109]:
#steam_df_filtered['release_date'] = pd.to_datetime(steam_df_filtered['release_date'].apply(lambda d: None if len(d) == 0 else d[:3] + ' 1, ' + d[4:8] if len(d) <= 8  else d))

steam_df_filtered.dropna(subset=['release_date'],inplace=True)
steam_df_filtered['release_date'].isnull().sum()

0

In [88]:
dateTimeSerie = pd.to_datetime(steam_df_filtered['release_date'], errors='coerce')

dateTimeSerieAjusted = steam_df_filtered[dateTimeSerie.isnull()]['release_date'].apply(lambda d: None if len(d) == 0 else d[:3] + ' 1, ' + d[4:8] if len(d) <= 8  else d)

dateTimeSerieAjusted

2832     Apr 1, 2022
3101     Dec 1, 2019
3417     Jul 1, 2018
3946     Feb 1, 2020
4934     Aug 1, 2017
5568     Jan 1, 2017
6919     Dec 1, 2015
6995     Dec 1, 2016
7377     Oct 1, 2020
7637     May 1, 2015
8290     Dec 1, 2019
8424     Sep 1, 2019
9121     Aug 1, 2015
9435     May 1, 2015
9690     Aug 1, 2014
9740     May 1, 2014
10069    May 1, 2014
10149           None
10386    Aug 1, 2013
10477           None
10555           None
10625           None
10640           None
10672           None
10686           None
10689           None
10770           None
10779           None
10940           None
10942           None
10943           None
10958    Oct 1, 2010
10959    Oct 1, 2010
10960    Oct 1, 2010
10988    Apr 1, 2010
11046           None
11047           None
11108           None
11139           None
11142           None
11151           None
11172           None
11173           None
11174           None
11175           None
11176           None
11177    Jul 1, 2010
11184    Jun 1, 2009
11225           None
11324           None
11621    Dec 1, 2012
11622           None
11839    Apr 1, 2019
12220    Jan 1, 2021
Name: release_date, dtype: object

### 2. o uso técnicas de estatística descritiva para compreender e descrever os dados. Use gráficos, tabelas e texto para descrever os seus achados.

### 3. calcule a média e o desvio padrão para todas as variáveis. Em alguma variável, essas duas medidas não bastam para descrever o problema? Por quê?

### 5. caso você encontre mais problemas na base (outliers, dados incompatíveis, problema de formato), realize pequenos reparos em uma base com problemas de qualidade. Descreva cada um dos problemas e enumere as dimensões de qualidade afetadas.

** Problemas encontrados**

- Jogos não lançados passaram pelo primeiro filtro, mas não servem para o propósito dessa análise, portanto foram desconsiderados
    - d
- Muitos jogos receberam um dado equivocado de duração vinda do HowLongToBeat (HLTB), para minimizar isso foi estabelecido que a similaridade do nome pesquisado com o resultado deve ser maior que 90%, aplicar um filtro 100% poderia remover vários títulos que estão com os dados corretos mas que por mudanças de nome na loja não tem um nome perfeitamente igual ao presente no HLTB
    - d
- Vários jogos até possuem cadastro no HLTB mas ninguém submeteu durações para eles, o que irá inutilizar a análise pois nenhum jogo tem duração zero, portanto foi imposto que a duração deve no mínimo superior a zero para ser um jogo válida para essa análise
    - d
- Dados incompletos de data de lançamento foram encontrados, após investigação foi identificado que se trata de jogos em acesso antecipado, por não ser foco dessa análise entender jogos nessa condição, eles foram descartados
    - d
- Também foi constatado que algumas datas não possuem dia, para elas será inferido o dia 1
    - d 
- Constatado também que jogos que não estão mais disponíveis na loja, não possuem uma data de lançamento, serão excluídos pois não se sabe a data em que foram excluídos
    - d

### 7. Normalize e escalonar dados da base

---